// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package mame

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TOK_NUM-0]
	_ = x[TOK_PLUS-1]
	_ = x[TOK_MINUS-2]
	_ = x[TOK_MUL-3]
	_ = x[TOK_DIV-4]
	_ = x[TOK_MOD-5]
	_ = x[TOK_LPAREN-6]
	_ = x[TOK_RPAREN-7]
	_ = x[TOK_LBRACE-8]
	_ = x[TOK_RBRACE-9]
	_ = x[TOK_IDENT-10]
	_ = x[TOK_ASSIGN-11]
	_ = x[TOK_EQ-12]
	_ = x[TOK_NE-13]
	_ = x[TOK_LT-14]
	_ = x[TOK_LE-15]
	_ = x[TOK_GT-16]
	_ = x[TOK_GE-17]
	_ = x[TOK_SEMI-18]
	_ = x[TOK_ARG-19]
	_ = x[TOK_STRING-20]
	_ = x[TOK_EOF-21]
}

const _TokenType_name = "TOK_NUMTOK_PLUSTOK_MINUSTOK_MULTOK_DIVTOK_MODTOK_LPARENTOK_RPARENTOK_LBRACETOK_RBRACETOK_IDENTTOK_ASSIGNTOK_EQTOK_NETOK_LTTOK_LETOK_GTTOK_GETOK_SEMITOK_ARGTOK_STRINGTOK_EOF"

var _TokenType_index = [...]uint8{0, 7, 15, 24, 31, 38, 45, 55, 65, 75, 85, 94, 104, 110, 116, 122, 128, 134, 140, 148, 155, 165, 172}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
